# Generated by Django 4.2.3 on 2023-07-24 07:24

from django.db import migrations, models
import petstagram_workshop.photos.validators


class Migration(migrations.Migration):
    dependencies = [
        ('photos', '0003_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(
                blank=True,
                upload_to='mediafiles/pet_photos/',
                validators=[petstagram_workshop.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
