# pets/models.py
from django.db import models
from django.template.defaultfilters import slugify

from petstagram_workshop.core.model_mixin import StrFromFieldsMixin


# Create your models here.
class Pet(StrFromFieldsMixin, models.Model):
    str_fields = ('id', 'name', 'slug')
    MAX_LEN_NAME = 30

    name = models.CharField(
        max_length=MAX_LEN_NAME,
        null=False,
        blank=False,
    )

    personal_photo = models.URLField(
        null=False,
        blank=False,
    )

    date_of_birth = models.DateField(
        blank=True,
        null=True,
    )

    slug = models.SlugField(
        # new
        unique=True,
        # editable=False,
        null=False,
        blank=True,
    )

    # autogenerated slug
    def save(self, *args, **kwargs):
        # Create/Update
        super().save(*args, **kwargs)

        if not self.slug:
            self.slug = slugify(f"{self.name}--{self.id}")
            # Update
        return super().save(*args, **kwargs)
